version: '3.8'
services:
  db:
    container_name: recipes_db
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:latest
    command: redis-server --bind redis --port 6379
  web:
    container_name: recipes_web
    build: .
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RECIPES_DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/0
    ports:
      - 3000:3000
    volumes:
      - .:/web
      - /web/vendor
      - /web/node_modules
    links:
      - db

      - mailcatcher

    stdin_open: true
    tty: true
    depends_on:
      - db
  sidekiq:
    container_name: recipes_sidekiq
    build: .
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/web
      - /web/node_modules
    links:
      - redis
      - db

      - mailcatcher


  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'


volumes:
  db-data:
    driver: local
