# default: &default
#   adapter: mysql2
#   encoding: utf8mb4
#   host: <%= ENV.fetch("RECIPES_DATABASE_HOST") { "localhost" } %>
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  adapter: mysql2
  database: recipes_development
  username: root
  password: password
  # socket: /tmp/mysql.sock
test:
  adapter: mysql2
  database: recipes_test
  username: root
  password: password
  # socket: /tmp/mysql.sock
# production:
#   <<: *default
#   database: recipes_production
#   username: recipes_production
#   password: <%= ENV["RECIPES_PASSWORD"] %>
# staging:
#   <<: *default
#   database: recipes_staging
#   username: recipes_staging
#   password: <%= ENV["RECIPES_PASSWORD"] %>
